name: Build And Deploy To Aliyun ECS
# 触发脚本的条件，develop分支push代码的时候
on:
  push:
    branches:
      - main
# 要执行的任务
jobs:
  # 任务名称
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境（必填）
    runs-on: ubuntu-latest
    # 任务步骤
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@v4
        with:
          path: main
      # 安装node
      - name: 安装node.js
        # 使用action库 actions/setup-node 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.2
      # 安装依赖
      - name: 安装依赖
        run: npm install
        working-directory: ./my-react-app <!-- Ensure this path is correct -->
      # 打包
      - name: 打包
        run: npm run build
        working-directory: ./my-react-app <!-- Ensure this path is correct -->
      # 上传打包文件到远程服务器
      - name: 上传文件到远程服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "./dist/*"
          target: "/www/wwwroot/dist"